spring:
  application:
    name: event-sorucing
  datasource:
    url: jdbc:h2:mem:eventstore
    driver-class-name: org.h2.Driver
    username: dbUser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql : true
  h2:
    console:
      enabled: true
